// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYpKolqXV8Q7ceT8YZHthSFvs0oG-fOkE',
    appId: '1:27770271794:web:69a9ef03f2e54de22b642b',
    messagingSenderId: '27770271794',
    projectId: 'memorygameapp-c304c',
    authDomain: 'memorygameapp-c304c.firebaseapp.com',
    databaseURL: 'https://memorygameapp-c304c-default-rtdb.firebaseio.com',
    storageBucket: 'memorygameapp-c304c.firebasestorage.app',
    measurementId: 'G-ETBSBGX6WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKXFT5xpLavv0rPoXzzQfdJr99TlZIoA',
    appId: '1:27770271794:android:f8d3d0aba89dc22c2b642b',
    messagingSenderId: '27770271794',
    projectId: 'memorygameapp-c304c',
    databaseURL: 'https://memorygameapp-c304c-default-rtdb.firebaseio.com',
    storageBucket: 'memorygameapp-c304c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUH6Q0dekOKro9uv8lLk4avFFyT5Fz8NE',
    appId: '1:27770271794:ios:0f867a3a83e4a3bb2b642b',
    messagingSenderId: '27770271794',
    projectId: 'memorygameapp-c304c',
    databaseURL: 'https://memorygameapp-c304c-default-rtdb.firebaseio.com',
    storageBucket: 'memorygameapp-c304c.firebasestorage.app',
    iosBundleId: 'com.example.memoryGameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUH6Q0dekOKro9uv8lLk4avFFyT5Fz8NE',
    appId: '1:27770271794:ios:0f867a3a83e4a3bb2b642b',
    messagingSenderId: '27770271794',
    projectId: 'memorygameapp-c304c',
    databaseURL: 'https://memorygameapp-c304c-default-rtdb.firebaseio.com',
    storageBucket: 'memorygameapp-c304c.firebasestorage.app',
    iosBundleId: 'com.example.memoryGameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYpKolqXV8Q7ceT8YZHthSFvs0oG-fOkE',
    appId: '1:27770271794:web:1c07dd5ca54945842b642b',
    messagingSenderId: '27770271794',
    projectId: 'memorygameapp-c304c',
    authDomain: 'memorygameapp-c304c.firebaseapp.com',
    databaseURL: 'https://memorygameapp-c304c-default-rtdb.firebaseio.com',
    storageBucket: 'memorygameapp-c304c.firebasestorage.app',
    measurementId: 'G-J7ZKFN9V9Y',
  );

}